# Generated file - do not commit this file.
description: "The web implementation of firebase_auth"
homepage: "https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_auth/firebase_auth_web"
name: "firebase_auth_web"
version: "1.0.5"
dependencies: 
  http_parser: "^4.0.0"
  intl: "^0.17.0"
  js: "^0.6.3"
  meta: "^1.3.0"
  firebase_auth_platform_interface: 
    path: "C:\\Users\\Ben White\\Documents\\git\\flutterfire\\packages\\firebase_auth\\firebase_auth_platform_interface"
  firebase_core: 
    path: "C:\\Users\\Ben White\\Documents\\git\\flutterfire\\packages\\firebase_core\\firebase_core"
  firebase_core_web: 
    path: "C:\\Users\\Ben White\\Documents\\git\\flutterfire\\packages\\firebase_core\\firebase_core_web"
  flutter: 
    sdk: "flutter"
  flutter_web_plugins: 
    sdk: "flutter"
dependency_overrides: 
  firebase_auth: 
    path: "C:\\Users\\Ben White\\Documents\\git\\flutterfire\\packages\\firebase_auth\\firebase_auth"
  firebase_auth_platform_interface: 
    path: "C:\\Users\\Ben White\\Documents\\git\\flutterfire\\packages\\firebase_auth\\firebase_auth_platform_interface"
  firebase_core: 
    path: "C:\\Users\\Ben White\\Documents\\git\\flutterfire\\packages\\firebase_core\\firebase_core"
  firebase_core_platform_interface: 
    path: "C:\\Users\\Ben White\\Documents\\git\\flutterfire\\packages\\firebase_core\\firebase_core_platform_interface"
  firebase_core_web: 
    path: "C:\\Users\\Ben White\\Documents\\git\\flutterfire\\packages\\firebase_core\\firebase_core_web"
dev_dependencies: 
  firebase_auth: 
    path: "C:\\Users\\Ben White\\Documents\\git\\flutterfire\\packages\\firebase_auth\\firebase_auth"
  firebase_core_platform_interface: 
    path: "C:\\Users\\Ben White\\Documents\\git\\flutterfire\\packages\\firebase_core\\firebase_core_platform_interface"
  flutter_test: 
    sdk: "flutter"
environment: 
  flutter: ">=1.12.13+hotfix.4"
  sdk: ">=2.12.0 <3.0.0"
flutter: 
  plugin: 
    platforms: 
      web: 
        fileName: "firebase_auth_web.dart"
        pluginClass: "FirebaseAuthWeb"
