# Generated file - do not commit this file.
description: "A common platform interface for the firebase_core plugin."
homepage: "https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_core/firebase_core_platform_interface"
name: "firebase_core_platform_interface"
version: "4.0.0"
dependencies: 
  meta: "^1.3.0"
  plugin_platform_interface: "^2.0.0"
  flutter: 
    sdk: "flutter"
dependency_overrides: 
dev_dependencies: 
  mockito: "^5.0.0"
  flutter_test: 
    sdk: "flutter"
environment: 
  flutter: ">=1.12.13+hotfix.5"
  sdk: ">=2.12.0 <3.0.0"
