# Generated file - do not commit this file.
description: "Flutter plugin for Google Dynamic Links for Firebase, an app solution for creating and handling links across multiple platforms."
homepage: "https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_dynamic_links"
name: "firebase_dynamic_links"
version: "2.0.0-dev.1"
dependencies: 
  firebase_core: 
    path: "C:\\Users\\Ben White\\Documents\\git\\flutterfire\\packages\\firebase_core\\firebase_core"
  flutter: 
    sdk: "flutter"
dependency_overrides: 
  firebase_core: 
    path: "C:\\Users\\Ben White\\Documents\\git\\flutterfire\\packages\\firebase_core\\firebase_core"
dev_dependencies: 
  pedantic: "^1.11.0"
  url_launcher: "^6.0.2"
  flutter_test: 
    sdk: "flutter"
environment: 
  flutter: ">=1.12.0"
  sdk: ">=2.12.0 <3.0.0"
flutter: 
  plugin: 
    platforms: 
      android: 
        package: "io.flutter.plugins.firebasedynamiclinks"
        pluginClass: "FirebaseDynamicLinksPlugin"
      ios: 
        pluginClass: "FLTFirebaseDynamicLinksPlugin"
