# Generated file - do not commit this file.
description: "Flutter plugin for Firebase machine learning vision services."
homepage: "https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_ml_vision"
name: "firebase_ml_vision"
version: "0.11.0+2"
dependencies: 
  flutter: 
    sdk: "flutter"
dependency_overrides: 
  firebase_core: 
    path: "C:\\Users\\Ben White\\Documents\\git\\flutterfire\\packages\\firebase_core\\firebase_core"
dev_dependencies: 
  pedantic: "^1.8.0"
  test: "any"
  firebase_core: 
    path: "C:\\Users\\Ben White\\Documents\\git\\flutterfire\\packages\\firebase_core\\firebase_core"
  flutter_driver: 
    sdk: "flutter"
  flutter_test: 
    sdk: "flutter"
environment: 
  flutter: ">=1.10.0"
  sdk: ">=2.12.0 <3.0.0"
flutter: 
  plugin: 
    platforms: 
      android: 
        package: "io.flutter.plugins.firebasemlvision"
        pluginClass: "FirebaseMlVisionPlugin"
      ios: 
        pluginClass: "FLTFirebaseMlVisionPlugin"
