# Generated file - do not commit this file.
description: "Flutter plugin for Google Analytics for Firebase, an app measurement solution that provides insight on app usage and user engagement on Android and iOS."
homepage: "https://firebase.flutter.dev/docs/analytics/overview"
name: "firebase_analytics"
repository: "https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_analytics/firebase_analytics"
version: "8.0.0-dev.2"
dependencies: 
  meta: "^1.3.0"
  firebase_analytics_platform_interface: 
    path: "C:\\Users\\Ben White\\Documents\\git\\flutterfire\\packages\\firebase_analytics\\firebase_analytics_platform_interface"
  firebase_analytics_web: 
    path: "C:\\Users\\Ben White\\Documents\\git\\flutterfire\\packages\\firebase_analytics\\firebase_analytics_web"
  firebase_core: 
    path: "C:\\Users\\Ben White\\Documents\\git\\flutterfire\\packages\\firebase_core\\firebase_core"
  flutter: 
    sdk: "flutter"
dependency_overrides: 
  firebase_analytics_platform_interface: 
    path: "C:\\Users\\Ben White\\Documents\\git\\flutterfire\\packages\\firebase_analytics\\firebase_analytics_platform_interface"
  firebase_analytics_web: 
    path: "C:\\Users\\Ben White\\Documents\\git\\flutterfire\\packages\\firebase_analytics\\firebase_analytics_web"
  firebase_core: 
    path: "C:\\Users\\Ben White\\Documents\\git\\flutterfire\\packages\\firebase_core\\firebase_core"
dev_dependencies: 
  mockito: "^5.0.0"
  pedantic: "^1.8.0"
  flutter_test: 
    sdk: "flutter"
environment: 
  flutter: ">=1.12.13+hotfix.5"
  sdk: ">=2.12.0 <3.0.0"
flutter: 
  plugin: 
    platforms: 
      android: 
        package: "io.flutter.plugins.firebaseanalytics"
        pluginClass: "FirebaseAnalyticsPlugin"
      ios: 
        pluginClass: "FLTFirebaseAnalyticsPlugin"
      web: 
        default_package: "firebase_analytics_web"
