# Generated file - do not commit this file.
description: "The web implementation of firebase_storage"
name: "firebase_storage_web"
repository: "https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_storage/firebase_storage_web"
version: "1.0.3"
dependencies: 
  async: "^2.5.0"
  http: "^0.13.0"
  js: "^0.6.3"
  meta: "^1.3.0"
  firebase_core: 
    path: "C:\\Users\\Ben White\\Documents\\git\\flutterfire\\packages\\firebase_core\\firebase_core"
  firebase_core_web: 
    path: "C:\\Users\\Ben White\\Documents\\git\\flutterfire\\packages\\firebase_core\\firebase_core_web"
  firebase_storage_platform_interface: 
    path: "C:\\Users\\Ben White\\Documents\\git\\flutterfire\\packages\\firebase_storage\\firebase_storage_platform_interface"
  flutter: 
    sdk: "flutter"
  flutter_web_plugins: 
    sdk: "flutter"
dependency_overrides: 
  firebase_core: 
    path: "C:\\Users\\Ben White\\Documents\\git\\flutterfire\\packages\\firebase_core\\firebase_core"
  firebase_core_platform_interface: 
    path: "C:\\Users\\Ben White\\Documents\\git\\flutterfire\\packages\\firebase_core\\firebase_core_platform_interface"
  firebase_core_web: 
    path: "C:\\Users\\Ben White\\Documents\\git\\flutterfire\\packages\\firebase_core\\firebase_core_web"
  firebase_storage_platform_interface: 
    path: "C:\\Users\\Ben White\\Documents\\git\\flutterfire\\packages\\firebase_storage\\firebase_storage_platform_interface"
dev_dependencies: 
  mockito: "^5.0.0"
  firebase_core_platform_interface: 
    path: "C:\\Users\\Ben White\\Documents\\git\\flutterfire\\packages\\firebase_core\\firebase_core_platform_interface"
  flutter_test: 
    sdk: "flutter"
environment: 
  flutter: ">=1.20.0"
  sdk: ">=2.12.0 <3.0.0"
flutter: 
  plugin: 
    platforms: 
      web: 
        fileName: "firebase_storage_web.dart"
        pluginClass: "FirebaseStorageWeb"
