# Generated file - do not commit this file.
author: "Flutter Team <flutter-dev@googlegroups.com>"
description: "Demonstrates how to use the firebase_storage plugin."
name: "firebase_storage_example"
dependencies: 
  image_picker: "^0.7.0"
  image_picker_for_web: "^2.0.0-nullsafety"
  firebase_core: 
    path: "C:\\Users\\Ben White\\Documents\\git\\flutterfire\\packages\\firebase_core\\firebase_core"
  firebase_storage: 
    path: "C:\\Users\\Ben White\\Documents\\git\\flutterfire\\packages\\firebase_storage\\firebase_storage"
  flutter: 
    sdk: "flutter"
dependency_overrides: 
  firebase_core: 
    path: "C:\\Users\\Ben White\\Documents\\git\\flutterfire\\packages\\firebase_core\\firebase_core"
  firebase_core_platform_interface: 
    path: "C:\\Users\\Ben White\\Documents\\git\\flutterfire\\packages\\firebase_core\\firebase_core_platform_interface"
  firebase_core_web: 
    path: "C:\\Users\\Ben White\\Documents\\git\\flutterfire\\packages\\firebase_core\\firebase_core_web"
  firebase_storage: 
    path: "C:\\Users\\Ben White\\Documents\\git\\flutterfire\\packages\\firebase_storage\\firebase_storage"
  firebase_storage_platform_interface: 
    path: "C:\\Users\\Ben White\\Documents\\git\\flutterfire\\packages\\firebase_storage\\firebase_storage_platform_interface"
  firebase_storage_web: 
    path: "C:\\Users\\Ben White\\Documents\\git\\flutterfire\\packages\\firebase_storage\\firebase_storage_web"
dev_dependencies: 
  drive: "0.0.1-6.0.pre"
  test: "any"
  flutter_driver: 
    sdk: "flutter"
environment: 
  sdk: ">=2.12.0 <3.0.0"
flutter: 
  assets: 
    - "assets/hello.txt"
  uses-material-design: true
