# Generated file - do not commit this file.
description: "Flutter plugin for Cloud Firestore, a cloud-hosted, noSQL database with live synchronization and offline support on Android and iOS."
homepage: "https://firebase.flutter.dev/docs/firestore/overview"
name: "cloud_firestore"
repository: "https://github.com/FirebaseExtended/flutterfire/tree/master/packages/cloud_firestore/cloud_firestore"
version: "1.0.4"
dependencies: 
  meta: "^1.3.0"
  cloud_firestore_platform_interface: 
    path: "C:\\Users\\Ben White\\Documents\\git\\flutterfire\\packages\\cloud_firestore\\cloud_firestore_platform_interface"
  cloud_firestore_web: 
    path: "C:\\Users\\Ben White\\Documents\\git\\flutterfire\\packages\\cloud_firestore\\cloud_firestore_web"
  firebase_core: 
    path: "C:\\Users\\Ben White\\Documents\\git\\flutterfire\\packages\\firebase_core\\firebase_core"
  firebase_core_platform_interface: 
    path: "C:\\Users\\Ben White\\Documents\\git\\flutterfire\\packages\\firebase_core\\firebase_core_platform_interface"
  flutter: 
    sdk: "flutter"
dependency_overrides: 
  cloud_firestore_platform_interface: 
    path: "C:\\Users\\Ben White\\Documents\\git\\flutterfire\\packages\\cloud_firestore\\cloud_firestore_platform_interface"
  cloud_firestore_web: 
    path: "C:\\Users\\Ben White\\Documents\\git\\flutterfire\\packages\\cloud_firestore\\cloud_firestore_web"
  firebase_core: 
    path: "C:\\Users\\Ben White\\Documents\\git\\flutterfire\\packages\\firebase_core\\firebase_core"
  firebase_core_platform_interface: 
    path: "C:\\Users\\Ben White\\Documents\\git\\flutterfire\\packages\\firebase_core\\firebase_core_platform_interface"
dev_dependencies: 
  mockito: "^5.0.0"
  test: "any"
  flutter_test: 
    sdk: "flutter"
environment: 
  flutter: ">=1.12.13+hotfix.4"
  sdk: ">=2.12.0 <3.0.0"
flutter: 
  plugin: 
    platforms: 
      android: 
        package: "io.flutter.plugins.firebase.firestore"
        pluginClass: "FlutterFirebaseFirestorePlugin"
      ios: 
        pluginClass: "FLTFirebaseFirestorePlugin"
      macos: 
        pluginClass: "FLTFirebaseFirestorePlugin"
      web: 
        default_package: "cloud_firestore_web"
