name: cloud_firestore
description:
  Flutter plugin for Cloud Firestore, a cloud-hosted, noSQL database with
  live synchronization and offline support on Android and iOS.
homepage: https://firebase.google.com/docs/firestore
repository: https://github.com/firebase/flutterfire/tree/master/packages/cloud_firestore/cloud_firestore
version: 4.5.3

false_secrets:
  - example/**
  - dartpad/**

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: ">=1.12.13+hotfix.5"

dependencies:
  cloud_firestore_platform_interface:
    git:
      url: https://github.com/bswhite1/flutterfire.git
      path: packages/cloud_firestore/cloud_firestore_platform_interface
      ref: snapshot_changes_git_paths

  cloud_firestore_web:
    git:
      url: https://github.com/bswhite1/flutterfire.git
      path: packages/cloud_firestore/cloud_firestore_web
      ref: snapshot_changes_git_paths

  collection: ^1.0.0
  firebase_core: ^2.10.0
  firebase_core_platform_interface: ^4.6.0

  flutter:
    sdk: flutter
  meta: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: io.flutter.plugins.firebase.firestore
        pluginClass: FlutterFirebaseFirestorePlugin
      ios:
        pluginClass: FLTFirebaseFirestorePlugin
      macos:
        pluginClass: FLTFirebaseFirestorePlugin
      web:
        default_package: cloud_firestore_web
