# Generated file - do not commit this file.
description: "Demonstrates how to use the firebase_dynamic_links plugin."
name: "firebase_dynamic_links_example"
dependencies: 
  url_launcher: "^6.0.2"
  firebase_core: 
    path: "C:\\Users\\Ben White\\Documents\\git\\flutterfire\\packages\\firebase_core\\firebase_core"
  firebase_dynamic_links: 
    path: "C:\\Users\\Ben White\\Documents\\git\\flutterfire\\packages\\firebase_dynamic_links"
  flutter: 
    sdk: "flutter"
dependency_overrides: 
  firebase_core: 
    path: "C:\\Users\\Ben White\\Documents\\git\\flutterfire\\packages\\firebase_core\\firebase_core"
  firebase_core_platform_interface: 
    path: "C:\\Users\\Ben White\\Documents\\git\\flutterfire\\packages\\firebase_core\\firebase_core_platform_interface"
  firebase_core_web: 
    path: "C:\\Users\\Ben White\\Documents\\git\\flutterfire\\packages\\firebase_core\\firebase_core_web"
  firebase_dynamic_links: 
    path: "C:\\Users\\Ben White\\Documents\\git\\flutterfire\\packages\\firebase_dynamic_links"
dev_dependencies: 
  pedantic: "^1.11.0"
environment: 
  flutter: ">=1.12.0"
  sdk: ">=2.12.0 <3.0.0"
flutter: 
  uses-material-design: true
