# Generated file - do not commit this file.
description: "Flutter plugin for Firebase Cloud Messaging, a cross-platform messaging solution that lets you reliably deliver messages on Android and iOS."
homepage: "https://firebase.flutter.dev/docs/messaging/overview"
name: "firebase_messaging"
repository: "https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_messaging/firebase_messaging"
version: "9.1.1"
dependencies: 
  meta: "^1.3.0"
  firebase_core: 
    path: "C:\\Users\\Ben White\\Documents\\git\\flutterfire\\packages\\firebase_core\\firebase_core"
  firebase_core_platform_interface: 
    path: "C:\\Users\\Ben White\\Documents\\git\\flutterfire\\packages\\firebase_core\\firebase_core_platform_interface"
  firebase_messaging_platform_interface: 
    path: "C:\\Users\\Ben White\\Documents\\git\\flutterfire\\packages\\firebase_messaging\\firebase_messaging_platform_interface"
  firebase_messaging_web: 
    path: "C:\\Users\\Ben White\\Documents\\git\\flutterfire\\packages\\firebase_messaging\\firebase_messaging_web"
  flutter: 
    sdk: "flutter"
dependency_overrides: 
  firebase_core: 
    path: "C:\\Users\\Ben White\\Documents\\git\\flutterfire\\packages\\firebase_core\\firebase_core"
  firebase_core_platform_interface: 
    path: "C:\\Users\\Ben White\\Documents\\git\\flutterfire\\packages\\firebase_core\\firebase_core_platform_interface"
  firebase_messaging_platform_interface: 
    path: "C:\\Users\\Ben White\\Documents\\git\\flutterfire\\packages\\firebase_messaging\\firebase_messaging_platform_interface"
  firebase_messaging_web: 
    path: "C:\\Users\\Ben White\\Documents\\git\\flutterfire\\packages\\firebase_messaging\\firebase_messaging_web"
dev_dependencies: 
  async: "^2.5.0"
  mockito: "^5.0.0"
  plugin_platform_interface: "^2.0.0"
  test: "any"
  flutter_test: 
    sdk: "flutter"
environment: 
  flutter: ">=1.12.13+hotfix.5"
  sdk: ">=2.12.0 <3.0.0"
flutter: 
  plugin: 
    platforms: 
      android: 
        package: "io.flutter.plugins.firebase.messaging"
        pluginClass: "FlutterFirebaseMessagingPlugin"
      ios: 
        pluginClass: "FLTFirebaseMessagingPlugin"
      macos: 
        pluginClass: "FLTFirebaseMessagingPlugin"
      web: 
        default_package: "firebase_messaging_web"
