# Generated file - do not commit this file.
description: "Flutter plugin for Firebase Core, enabling connecting to multiple Firebase apps."
homepage: "https://firebase.flutter.dev/docs/core/usage"
name: "firebase_core"
repository: "https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_core/firebase_core"
version: "1.0.3"
dependencies: 
  meta: "^1.3.0"
  firebase_core_platform_interface: 
    path: "C:\\Users\\Ben White\\Documents\\git\\flutterfire\\packages\\firebase_core\\firebase_core_platform_interface"
  firebase_core_web: 
    path: "C:\\Users\\Ben White\\Documents\\git\\flutterfire\\packages\\firebase_core\\firebase_core_web"
  flutter: 
    sdk: "flutter"
dependency_overrides: 
  firebase_core_platform_interface: 
    path: "C:\\Users\\Ben White\\Documents\\git\\flutterfire\\packages\\firebase_core\\firebase_core_platform_interface"
  firebase_core_web: 
    path: "C:\\Users\\Ben White\\Documents\\git\\flutterfire\\packages\\firebase_core\\firebase_core_web"
dev_dependencies: 
  mockito: "^5.0.0"
  plugin_platform_interface: "^2.0.0"
  flutter_test: 
    sdk: "flutter"
environment: 
  flutter: ">=1.12.13+hotfix.5"
  sdk: ">=2.12.0 <3.0.0"
flutter: 
  plugin: 
    platforms: 
      android: 
        package: "io.flutter.plugins.firebase.core"
        pluginClass: "FlutterFirebaseCorePlugin"
      ios: 
        pluginClass: "FLTFirebaseCorePlugin"
      macos: 
        pluginClass: "FLTFirebaseCorePlugin"
      web: 
        default_package: "firebase_core_web"
