# Generated file - do not commit this file.
description: "A common platform interface for the firebase_storage plugin."
homepage: "https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_storage/firebase_storage_platform_interface"
name: "firebase_storage_platform_interface"
version: "2.0.1"
dependencies: 
  collection: "^1.15.0"
  meta: "^1.3.0"
  plugin_platform_interface: "^2.0.0"
  firebase_core: 
    path: "C:\\Users\\Ben White\\Documents\\git\\flutterfire\\packages\\firebase_core\\firebase_core"
  flutter: 
    sdk: "flutter"
dependency_overrides: 
  firebase_core: 
    path: "C:\\Users\\Ben White\\Documents\\git\\flutterfire\\packages\\firebase_core\\firebase_core"
  firebase_core_platform_interface: 
    path: "C:\\Users\\Ben White\\Documents\\git\\flutterfire\\packages\\firebase_core\\firebase_core_platform_interface"
dev_dependencies: 
  mockito: "^5.0.0"
  firebase_core_platform_interface: 
    path: "C:\\Users\\Ben White\\Documents\\git\\flutterfire\\packages\\firebase_core\\firebase_core_platform_interface"
  flutter_test: 
    sdk: "flutter"
environment: 
  flutter: ">=1.9.1+hotfix.5"
  sdk: ">=2.12.0 <3.0.0"
