# Generated file - do not commit this file.
description: "Flutter plugin for Firebase Cloud Storage, a powerful, simple, and cost-effective object storage service for Android and iOS."
homepage: "https://firebase.flutter.dev/docs/storage/overview"
name: "firebase_storage"
repository: "https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_storage/firebase_storage"
version: "8.0.3"
dependencies: 
  firebase_core: 
    path: "C:\\Users\\Ben White\\Documents\\git\\flutterfire\\packages\\firebase_core\\firebase_core"
  firebase_core_platform_interface: 
    path: "C:\\Users\\Ben White\\Documents\\git\\flutterfire\\packages\\firebase_core\\firebase_core_platform_interface"
  firebase_storage_platform_interface: 
    path: "C:\\Users\\Ben White\\Documents\\git\\flutterfire\\packages\\firebase_storage\\firebase_storage_platform_interface"
  firebase_storage_web: 
    path: "C:\\Users\\Ben White\\Documents\\git\\flutterfire\\packages\\firebase_storage\\firebase_storage_web"
  flutter: 
    sdk: "flutter"
dependency_overrides: 
  firebase_core: 
    path: "C:\\Users\\Ben White\\Documents\\git\\flutterfire\\packages\\firebase_core\\firebase_core"
  firebase_core_platform_interface: 
    path: "C:\\Users\\Ben White\\Documents\\git\\flutterfire\\packages\\firebase_core\\firebase_core_platform_interface"
  firebase_storage_platform_interface: 
    path: "C:\\Users\\Ben White\\Documents\\git\\flutterfire\\packages\\firebase_storage\\firebase_storage_platform_interface"
  firebase_storage_web: 
    path: "C:\\Users\\Ben White\\Documents\\git\\flutterfire\\packages\\firebase_storage\\firebase_storage_web"
dev_dependencies: 
  http: "^0.13.0"
  mockito: "^5.0.0"
  plugin_platform_interface: "^2.0.0"
  test: "any"
  flutter_test: 
    sdk: "flutter"
environment: 
  flutter: ">=1.12.13+hotfix.5"
  sdk: ">=2.12.0 <3.0.0"
flutter: 
  plugin: 
    platforms: 
      android: 
        package: "io.flutter.plugins.firebase.storage"
        pluginClass: "FlutterFirebaseStoragePlugin"
      ios: 
        pluginClass: "FLTFirebaseStoragePlugin"
      macos: 
        pluginClass: "FLTFirebaseStoragePlugin"
      web: 
        default_package: "firebase_storage_web"
