# Generated file - do not commit this file.
author: "Flutter Team <flutter-dev@googlegroups.com>"
description: "Demonstrates how to use the firebase_auth plugin."
name: "firebase_auth_example"
dependencies: 
  flutter_signin_button: "^1.0.0"
  google_sign_in: "^5.0.0-nullsafety"
  firebase_auth: 
    path: "C:\\Users\\Ben White\\Documents\\git\\flutterfire\\packages\\firebase_auth\\firebase_auth"
  firebase_core: 
    path: "C:\\Users\\Ben White\\Documents\\git\\flutterfire\\packages\\firebase_core\\firebase_core"
  firebase_dynamic_links: 
    path: "C:\\Users\\Ben White\\Documents\\git\\flutterfire\\packages\\firebase_dynamic_links"
  flutter: 
    sdk: "flutter"
dependency_overrides: 
  firebase_auth: 
    path: "C:\\Users\\Ben White\\Documents\\git\\flutterfire\\packages\\firebase_auth\\firebase_auth"
  firebase_auth_platform_interface: 
    path: "C:\\Users\\Ben White\\Documents\\git\\flutterfire\\packages\\firebase_auth\\firebase_auth_platform_interface"
  firebase_auth_web: 
    path: "C:\\Users\\Ben White\\Documents\\git\\flutterfire\\packages\\firebase_auth\\firebase_auth_web"
  firebase_core: 
    path: "C:\\Users\\Ben White\\Documents\\git\\flutterfire\\packages\\firebase_core\\firebase_core"
  firebase_core_platform_interface: 
    path: "C:\\Users\\Ben White\\Documents\\git\\flutterfire\\packages\\firebase_core\\firebase_core_platform_interface"
  firebase_core_web: 
    path: "C:\\Users\\Ben White\\Documents\\git\\flutterfire\\packages\\firebase_core\\firebase_core_web"
  firebase_dynamic_links: 
    path: "C:\\Users\\Ben White\\Documents\\git\\flutterfire\\packages\\firebase_dynamic_links"
dev_dependencies: 
  drive: "0.0.1-6.0.pre"
  http: "^0.13.0"
  test: "any"
  flutter_driver: 
    sdk: "flutter"
environment: 
  sdk: ">=2.12.0 <3.0.0"
flutter: 
  uses-material-design: true
