# Generated file - do not commit this file.
description: "The web implementation of firebase_core"
homepage: "https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_core/firebase_core_web"
name: "firebase_core_web"
version: "1.0.2"
dependencies: 
  js: "^0.6.3"
  meta: "^1.3.0"
  firebase_core_platform_interface: 
    path: "C:\\Users\\Ben White\\Documents\\git\\flutterfire\\packages\\firebase_core\\firebase_core_platform_interface"
  flutter: 
    sdk: "flutter"
  flutter_web_plugins: 
    sdk: "flutter"
dependency_overrides: 
  firebase_core: 
    path: "C:\\Users\\Ben White\\Documents\\git\\flutterfire\\packages\\firebase_core\\firebase_core"
  firebase_core_platform_interface: 
    path: "C:\\Users\\Ben White\\Documents\\git\\flutterfire\\packages\\firebase_core\\firebase_core_platform_interface"
dev_dependencies: 
  firebase_core: 
    path: "C:\\Users\\Ben White\\Documents\\git\\flutterfire\\packages\\firebase_core\\firebase_core"
  flutter_test: 
    sdk: "flutter"
environment: 
  flutter: ">=1.12.13+hotfix.5"
  sdk: ">=2.12.0 <3.0.0"
flutter: 
  plugin: 
    platforms: 
      web: 
        fileName: "firebase_core_web.dart"
        pluginClass: "FirebaseCoreWeb"
