# Generated file - do not commit this file.
description: "The web implementation of firebase_analytics"
homepage: "https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_analytics/firebase_analytics_web"
name: "firebase_analytics_web"
version: "0.3.0-dev.0"
dependencies: 
  firebase: "^9.0.1"
  meta: "^1.3.0"
  firebase_analytics_platform_interface: 
    path: "C:\\Users\\Ben White\\Documents\\git\\flutterfire\\packages\\firebase_analytics\\firebase_analytics_platform_interface"
  flutter: 
    sdk: "flutter"
  flutter_web_plugins: 
    sdk: "flutter"
dependency_overrides: 
  firebase_analytics_platform_interface: 
    path: "C:\\Users\\Ben White\\Documents\\git\\flutterfire\\packages\\firebase_analytics\\firebase_analytics_platform_interface"
dev_dependencies: 
  mockito: "^5.0.0"
  flutter_test: 
    sdk: "flutter"
environment: 
  flutter: ">=1.12.13+hotfix.4"
  sdk: ">=2.12.0 <3.0.0"
flutter: 
  plugin: 
    platforms: 
      web: 
        fileName: "firebase_analytics_web.dart"
        pluginClass: "FirebaseAnalyticsWeb"
