# Generated file - do not commit this file.
description: "Demonstrates how to use the firebase_ml_custom plugin."
name: "firebase_ml_custom_example"
publish_to: "none"
dependencies: 
  cupertino_icons: "^0.1.3"
  image_picker: "^0.6.0"
  tflite: "1.1.1"
  firebase_core: 
    path: "C:\\Users\\Ben White\\Documents\\git\\flutterfire\\packages\\firebase_core\\firebase_core"
  firebase_ml_custom: 
    path: "C:\\Users\\Ben White\\Documents\\git\\flutterfire\\packages\\firebase_ml_custom"
  flutter: 
    sdk: "flutter"
dependency_overrides: 
  firebase_core: 
    path: "C:\\Users\\Ben White\\Documents\\git\\flutterfire\\packages\\firebase_core\\firebase_core"
  firebase_core_platform_interface: 
    path: "C:\\Users\\Ben White\\Documents\\git\\flutterfire\\packages\\firebase_core\\firebase_core_platform_interface"
  firebase_core_web: 
    path: "C:\\Users\\Ben White\\Documents\\git\\flutterfire\\packages\\firebase_core\\firebase_core_web"
  firebase_ml_custom: 
    path: "C:\\Users\\Ben White\\Documents\\git\\flutterfire\\packages\\firebase_ml_custom"
dev_dependencies: 
  e2e: "^0.2.1"
  path: "^1.6.2"
  path_provider: "^0.5.0+1"
  pedantic: "^1.8.0"
  test: "any"
  flutter_driver: 
    sdk: "flutter"
  flutter_test: 
    sdk: "flutter"
environment: 
  sdk: ">=2.12.0 <3.0.0"
flutter: 
  assets: 
    - "assets/labels_mobilenet_v1_224.txt"
  uses-material-design: true
