name: cloud_firestore_web
description: The web implementation of cloud_firestore
homepage: https://github.com/firebase/flutterfire/tree/master/packages/cloud_firestore/cloud_firestore_web
repository: https://github.com/firebase/flutterfire/tree/master/packages/cloud_firestore/cloud_firestore_web

version: 3.4.2

environment:
  sdk: '>=2.18.0 <3.0.0'
  flutter: '>=1.20.0'

dependencies:
  _flutterfire_internals: ^1.1.1
  cloud_firestore_platform_interface:
    git:
      url: https://github.com/bswhite1/flutterfire.git
      path: packages/cloud_firestore/cloud_firestore_platform_interface
      ref: snapshot_changes_git_paths
  collection: ^1.0.0
  firebase_core: ^2.10.0
  firebase_core_web: ^2.3.0
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  js: ^0.6.3

dev_dependencies:
  firebase_core_platform_interface: ^4.6.0
  flutter_test:
    sdk: flutter
  mockito: ^5.0.0

flutter:
  plugin:
    platforms:
      web:
        pluginClass: FirebaseFirestoreWeb
        fileName: cloud_firestore_web.dart
