# Generated file - do not commit this file.
description: "Flutter plugin for Firebase Database, a cloud-hosted NoSQL database with realtime data syncing across Android and iOS clients, and offline access."
homepage: "https://firebase.flutter.dev/docs/database/overview"
name: "firebase_database"
repository: "https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_database"
version: "6.1.2"
dependencies: 
  firebase_core: 
    path: "C:\\Users\\Ben White\\Documents\\git\\flutterfire\\packages\\firebase_core\\firebase_core"
  flutter: 
    sdk: "flutter"
dependency_overrides: 
  firebase_core: 
    path: "C:\\Users\\Ben White\\Documents\\git\\flutterfire\\packages\\firebase_core\\firebase_core"
  firebase_core_platform_interface: 
    path: "C:\\Users\\Ben White\\Documents\\git\\flutterfire\\packages\\firebase_core\\firebase_core_platform_interface"
dev_dependencies: 
  mockito: "^5.0.0"
  pedantic: "^1.8.0"
  test: "any"
  firebase_core_platform_interface: 
    path: "C:\\Users\\Ben White\\Documents\\git\\flutterfire\\packages\\firebase_core\\firebase_core_platform_interface"
  flutter_test: 
    sdk: "flutter"
environment: 
  flutter: ">=1.12.13+hotfix.5"
  sdk: ">=2.12.0 <3.0.0"
flutter: 
  plugin: 
    platforms: 
      android: 
        package: "io.flutter.plugins.firebase.database"
        pluginClass: "FirebaseDatabasePlugin"
      ios: 
        pluginClass: "FLTFirebaseDatabasePlugin"
      macos: 
        pluginClass: "FLTFirebaseDatabasePlugin"
