# Generated file - do not commit this file.
description: "A common platform interface for the firebase_analytics plugin."
homepage: "https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_analytics/firebase_analytics_platform_interface"
name: "firebase_analytics_platform_interface"
version: "2.0.0-dev.0"
dependencies: 
  meta: "^1.3.0"
  flutter: 
    sdk: "flutter"
dependency_overrides: 
dev_dependencies: 
  pedantic: "^1.8.0"
  flutter_test: 
    sdk: "flutter"
environment: 
  flutter: ">=1.9.1+hotfix.5"
  sdk: ">=2.12.0 <3.0.0"
